var myJsonData = [{
	"id": "1",
	"longitudeOffset": "-10",
	"latitudeOffset": "0",
	"description": "West",
	"altitude": "100.0",
	"name": "POI_W"
}, {
	"id": "2",
	"longitudeOffset": "-7",
	"latitudeOffset": "7",
	"description": "NorthWest",
	"altitude": "100.0",
	"name": "POI_NW"
}, {
	"id": "3",
	"longitudeOffset": "0",
	"latitudeOffset": "10",
	"description": "North",
	"altitude": "100.0",
	"name": "POI_N"
}, {
	"id": "4",
	"longitudeOffset": "7",
	"latitudeOffset": "7",
	"description": "NorthEast",
	"altitude": "100.0",
	"name": "POI_NE"
}, {
	"id": "5",
	"longitudeOffset": "10",
	"latitudeOffset": "0",
	"description": "East",
	"altitude": "100.0",
	"name": "POI_E"
}, {
	"id": "6",
	"longitudeOffset": "7",
	"latitudeOffset": "-7",
	"description": "SouthEast",
	"altitude": "100.0",
	"name": "POI_SE"
}, {
	"id": "7",
	"longitudeOffset": "0",
	"latitudeOffset": "-10",
	"description": "South",
	"altitude": "100.0",
	"name": "POI_S"
}, {
	"id": "8",
	"longitudeOffset": "-7",
	"latitudeOffset": "-7",
	"description": "SouthWest",
	"altitude": "100.0",
	"name": "POI_SW"
}];